/**
 * The hands-free conductor — the all-voice heart of Suara. Once started, it drives the
 * whole lesson with no taps and no reading (CLAUDE.md: "fully operable by voice; visual
 * UI is optional aid"). Per turn it:
 *
 *   fetch next turn → play the teacher (setup [+ taught word] [+ classmate]) → "your turn"
 *   earcon → record a FIXED window → auto-submit → play the spoken correction + the native
 *   model → warm earcon → advance.
 *
 * Capture is a fixed listening window (sized by the server's recordMs) rather than
 * silence-detection — predictable and dependency-free. Pause / resume / repeat are
 * optional fallbacks (tap anywhere); the default path needs no interaction at all.
 *
 * Turns are single-use server-side, so every advance fetches a NEW turn; a missed block
 * is re-surfaced by the invisible SRS later (an MT invariant), never replayed in place.
 */

import { useCallback, useEffect, useRef, useState } from 'react';
import type { AttemptResult, PromptPacket, SessionApi } from '../api/types';
import type { AudioIO, AudioSource } from '../audio/types';
import yourTurnWav from '../../assets/earcons/your-turn.wav';
import thinkingWav from '../../assets/earcons/thinking.wav';
import gotItWav from '../../assets/earcons/got-it.wav';
import againWav from '../../assets/earcons/again.wav';

// Bundled cue assets (generated by scripts/gen-earcons.mjs).
const EARCON = {
  yourTurn: yourTurnWav,
  thinking: thinkingWav,
  gotIt: gotItWav,
  again: againWav,
};

const DEFAULT_RECORD_MS = 6000;
const GAP_MS = 650; // a breath between turns

export type ConductorPhase =
  | 'idle'
  | 'loading'
  | 'teaching' // the teacher is speaking (setup / taught word / classmate)
  | 'listening' // recording the learner (fixed window)
  | 'scoring' // submitting + waiting on feedback
  | 'feedback' // playing the spoken correction + native model
  | 'paused'
  | 'error';

export interface ConductorState {
  phase: ConductorPhase;
  prompt: PromptPacket | null;
  attempt: AttemptResult | null;
  error: string | null;
  /** 0..1 across the listening window — drives the optional countdown ring */
  listenProgress: number;
  /** running session spend (USD), in-memory only */
  spend: number;
}

const initial: ConductorState = {
  phase: 'idle',
  prompt: null,
  attempt: null,
  error: null,
  listenProgress: 0,
  spend: 0,
};

export function useConductor(api: SessionApi, audio: AudioIO) {
  const [state, setState] = useState<ConductorState>(initial);
  const merge = useCallback((p: Partial<ConductorState>) => setState((s) => ({ ...s, ...p })), []);

  // Cancellation: each run owns a generation; bumping `gen` (stop / restart / unmount)
  // makes the in-flight loop bail at its next checkpoint.
  const gen = useRef(0);
  const pausedRef = useRef(false);
  const resumeRef = useRef<(() => void) | null>(null);
  // The current turn's replayable clips, for the "repeat" gesture.
  const replayRef = useRef<AudioSource[]>([]);

  const alive = (myGen: number) => myGen === gen.current;

  const sleep = (ms: number, myGen: number) =>
    new Promise<void>((res) => {
      const t = setTimeout(res, ms);
      // If cancelled mid-sleep, resolve early so the loop can bail promptly.
      const i = setInterval(() => {
        if (!alive(myGen)) {
          clearTimeout(t);
          clearInterval(i);
          res();
        }
      }, 80);
      setTimeout(() => clearInterval(i), ms + 1);
    });

  const playSafe = useCallback(
    async (source: AudioSource | undefined | null) => {
      if (!source) return; // empty url / missing earcon
      try {
        await audio.play(source);
      } catch (e) {
        console.warn('audio playback failed:', e);
      }
    },
    [audio],
  );

  /** Park at a pause if requested; return false if the run was cancelled meanwhile. */
  const checkpoint = useCallback(
    async (myGen: number): Promise<boolean> => {
      if (!alive(myGen)) return false;
      if (pausedRef.current) {
        merge({ phase: 'paused' });
        await new Promise<void>((res) => {
          resumeRef.current = res;
        });
        resumeRef.current = null;
        if (!alive(myGen)) return false;
      }
      return true;
    },
    [merge],
  );

  const runListen = useCallback(
    async (myGen: number, recordMs: number) => {
      merge({ phase: 'listening', listenProgress: 0 });
      await audio.startRecording();
      const step = 100;
      for (let elapsed = 0; elapsed < recordMs; elapsed += step) {
        if (!alive(myGen)) break;
        merge({ listenProgress: Math.min(1, elapsed / recordMs) });
        await sleep(step, myGen);
      }
      return audio.stopRecording();
    },
    // sleep/merge are stable enough; audio is stable from the memoized AudioIO.
    [audio, merge],
  );

  const loop = useCallback(
    async (myGen: number) => {
      try {
        while (alive(myGen)) {
          if (!(await checkpoint(myGen))) return;

          // 1. PLAN
          merge({ phase: 'loading', attempt: null, listenProgress: 0 });
          const prompt = await api.nextPrompt();
          if (!alive(myGen)) return;
          setState((s) => ({ ...s, prompt, spend: s.spend + (prompt.costUsd ?? 0) }));

          // 2. TEACHER speaks: setup → taught word (introduce) → classmate (if any)
          merge({ phase: 'teaching' });
          replayRef.current = [prompt.setupAudioUrl, prompt.teach?.modelAudioUrl, prompt.classmateAudioUrl].filter(
            (x): x is string => !!x,
          );
          await playSafe(prompt.setupAudioUrl);
          if (!(await checkpoint(myGen))) return;
          await playSafe(prompt.teach?.modelAudioUrl);
          await playSafe(prompt.classmateAudioUrl);
          if (!(await checkpoint(myGen))) return;

          // 3. YOUR TURN → record a fixed window → submit
          await playSafe(EARCON.yourTurn);
          const rec = await runListen(myGen, prompt.recordMs ?? DEFAULT_RECORD_MS);
          if (!alive(myGen)) return;

          merge({ phase: 'scoring' });
          void playSafe(EARCON.thinking); // soft cue so the wait never feels frozen
          const attempt = await api.submitAttempt(prompt.turnId, rec);
          if (!alive(myGen)) return;
          setState((s) => ({ ...s, attempt, spend: s.spend + (attempt.costUsd ?? 0) }));

          // 4. FEEDBACK: spoken warm cue → native model → warm earcon
          merge({ phase: 'feedback' });
          replayRef.current = [attempt.correctionAudioUrl, attempt.modelAudioUrl].filter((x): x is string => !!x);
          await playSafe(attempt.correctionAudioUrl);
          await playSafe(attempt.modelAudioUrl);
          await playSafe(attempt.verdict === 'correct' ? EARCON.gotIt : EARCON.again);
          if (!(await checkpoint(myGen))) return;

          // 5. ADVANCE (a breath, then the next turn — SRS decides what resurfaces)
          await sleep(GAP_MS, myGen);
        }
      } catch (e) {
        if (alive(myGen)) merge({ phase: 'error', error: e instanceof Error ? e.message : String(e) });
      }
    },
    [api, checkpoint, merge, playSafe, runListen],
  );

  const start = useCallback(() => {
    gen.current += 1;
    pausedRef.current = false;
    void loop(gen.current);
  }, [loop]);

  const stop = useCallback(() => {
    gen.current += 1; // cancels the in-flight loop at its next checkpoint
    pausedRef.current = false;
    resumeRef.current?.();
    resumeRef.current = null;
  }, []);

  const pause = useCallback(() => {
    pausedRef.current = true;
  }, []);

  const resume = useCallback(() => {
    pausedRef.current = false;
    resumeRef.current?.();
  }, []);

  /** Replay the current phase's clips (the optional "say that again" gesture). */
  const repeat = useCallback(async () => {
    for (const c of replayRef.current) await playSafe(c);
  }, [playSafe]);

  // Tear down on unmount: cancel the loop so no recorder/timer outlives the screen.
  useEffect(() => stop, [stop]);

  return { state, start, stop, pause, resume, repeat };
}
