/**
 * The hands-free conductor — the all-voice heart of Suara. Once started, it drives the
 * whole lesson with no taps and no reading (CLAUDE.md: "fully operable by voice; visual
 * UI is optional aid"). Per turn it:
 *
 *   fetch next turn → play the teacher (setup [+ taught word] [+ classmate]) → "your turn"
 *   earcon → record a FIXED window → auto-submit → play the spoken correction + the native
 *   model → warm earcon → advance.
 *
 * Capture is a fixed listening window (sized by the server's recordMs) rather than
 * silence-detection — predictable and dependency-free. Pause / resume / repeat are
 * optional fallbacks (tap anywhere); the default path needs no interaction at all.
 *
 * Turns are single-use server-side, so every advance fetches a NEW turn; a missed block
 * is re-surfaced by the invisible SRS later (an MT invariant), never replayed in place.
 */

import { useCallback, useEffect, useRef, useState } from 'react';
import type { AttemptResult, PromptPacket, SessionApi } from '../api/types';
import type { AudioIO, AudioSource } from '../audio/types';
import beginWav from '../../assets/earcons/begin.wav';
import yourTurnWav from '../../assets/earcons/your-turn.wav';
import thinkingBedWav from '../../assets/earcons/thinking-bed.wav';
import gotItWav from '../../assets/earcons/got-it.wav';
import againWav from '../../assets/earcons/again.wav';

// Bundled cue assets (generated by scripts/gen-earcons.mjs).
const EARCON = {
  begin: beginWav, // covers the first (un-prefetchable) turn's load
  yourTurn: yourTurnWav,
  thinkingBed: thinkingBedWav, // looped under the scoring wait
  gotIt: gotItWav,
  again: againWav,
};

// Natural turn-taking (VAD): we record until the learner stops speaking rather than for a
// fixed window. Tuned for construct-first MT, where a beginner thinks for a few seconds
// before speaking and pauses *between words* while building a sentence — so we're patient
// before onset and tolerant of mid-sentence gaps. Device-tuned starting points (dBFS / ms).
const MAX_RECORD_MS = 12_000; // hard safety cap on the whole window
const SILENCE_HOLD_MS = 1_500; // end this long after speech drops to the floor (rides over inter-word pauses)
const MIN_SPEAK_MS = 800; // ...but never before this much speaking, so a short answer isn't clipped
const NO_SPEECH_MS = 6_000; // patience before onset: ample think-time; if still silent, end gently
const ONSET_DB = 12; // this far above the calibrated floor counts as "speaking"
const POLL_MS = 90;
const GAP_MS = 650; // a breath between turns

export type ConductorPhase =
  | 'idle'
  | 'loading'
  | 'teaching' // the teacher is speaking (setup / taught word / classmate)
  | 'listening' // recording the learner (fixed window)
  | 'scoring' // submitting + waiting on feedback
  | 'feedback' // playing the spoken correction + native model
  | 'paused'
  | 'error';

export interface ConductorState {
  phase: ConductorPhase;
  prompt: PromptPacket | null;
  attempt: AttemptResult | null;
  error: string | null;
  /** 0..1 mic input level while listening — drives the orb's voice-reactive pulse (not a countdown) */
  level: number;
  /** running session spend (USD), in-memory only */
  spend: number;
}

const initial: ConductorState = {
  phase: 'idle',
  prompt: null,
  attempt: null,
  error: null,
  level: 0,
  spend: 0,
};

export function useConductor(api: SessionApi, audio: AudioIO) {
  const [state, setState] = useState<ConductorState>(initial);
  const merge = useCallback((p: Partial<ConductorState>) => setState((s) => ({ ...s, ...p })), []);

  // Cancellation: each run owns a generation; bumping `gen` (stop / restart / unmount)
  // makes the in-flight loop bail at its next checkpoint.
  const gen = useRef(0);
  const pausedRef = useRef(false);
  const resumeRef = useRef<(() => void) | null>(null);
  // The current turn's replayable clips, for the "repeat" gesture.
  const replayRef = useRef<AudioSource[]>([]);
  // The NEXT turn's plan, fetched during this turn's feedback so the learner never waits on
  // a cold `nextPrompt` at the top of a turn. Only valid once the prior attempt has been
  // submitted (planTurn reads SRS state that completeTurn writes), so it's set after submit.
  const nextPromptRef = useRef<Promise<PromptPacket> | null>(null);

  const alive = (myGen: number) => myGen === gen.current;

  const sleep = (ms: number, myGen: number) =>
    new Promise<void>((res) => {
      const t = setTimeout(res, ms);
      // If cancelled mid-sleep, resolve early so the loop can bail promptly.
      const i = setInterval(() => {
        if (!alive(myGen)) {
          clearTimeout(t);
          clearInterval(i);
          res();
        }
      }, 80);
      setTimeout(() => clearInterval(i), ms + 1);
    });

  const playSafe = useCallback(
    async (source: AudioSource | undefined | null) => {
      if (!source) return; // empty url / missing earcon
      try {
        await audio.play(source);
      } catch (e) {
        console.warn('audio playback failed:', e);
      }
    },
    [audio],
  );

  /** Park at a pause if requested; return false if the run was cancelled meanwhile. */
  const checkpoint = useCallback(
    async (myGen: number): Promise<boolean> => {
      if (!alive(myGen)) return false;
      if (pausedRef.current) {
        merge({ phase: 'paused' });
        await new Promise<void>((res) => {
          resumeRef.current = res;
        });
        resumeRef.current = null;
        if (!alive(myGen)) return false;
      }
      return true;
    },
    [merge],
  );

  /**
   * Record until the learner stops talking (natural turn-taking), not for a fixed window.
   * Polls the mic level: calibrates a noise floor, waits for speech onset, then ends after
   * a held silence — clamped by MIN_SPEAK_MS and a MAX_RECORD_MS safety cap. If metering is
   * unavailable (e.g. web), it falls back to the fixed `maxMs` window. The level also drives
   * the orb's pulse, so the learner can *see* they're being heard (optional visual aid).
   */
  const runListen = useCallback(
    async (myGen: number, fixedFallbackMs: number) => {
      merge({ phase: 'listening', level: 0 });
      await audio.startRecording();

      let floor = -50; // dBFS; adapts down to the actual room over the first few polls
      let calib = 0;
      let meteringSeen = false;
      let onset = false;
      let onsetAt = 0;
      let lastLoudAt = 0;

      for (let elapsed = 0; alive(myGen) && elapsed < MAX_RECORD_MS; elapsed += POLL_MS) {
        const lvl = audio.getInputLevel();
        if (lvl != null) {
          meteringSeen = true;
          merge({ level: Math.max(0, Math.min(1, (lvl + 50) / 50)) }); // ~[-50..0] dBFS → [0..1]
          if (!onset && calib < 5) {
            floor = Math.min(floor, lvl);
            calib += 1;
          }
          if (lvl > floor + ONSET_DB) {
            lastLoudAt = elapsed;
            if (!onset) {
              onset = true;
              onsetAt = elapsed;
            }
          }
        }
        if (meteringSeen) {
          // VAD path: end after a held silence post-onset, or gently if they never start.
          if (onset) {
            if (elapsed - onsetAt >= MIN_SPEAK_MS && elapsed - lastLoudAt >= SILENCE_HOLD_MS) break;
          } else if (elapsed >= NO_SPEECH_MS) {
            break;
          }
        } else if (elapsed >= fixedFallbackMs) {
          break; // no metering (e.g. web) → fall back to the server-sized fixed window
        }
        await sleep(POLL_MS, myGen);
      }

      merge({ level: 0 });
      return audio.stopRecording();
    },
    // sleep/merge are stable enough; audio is stable from the memoized AudioIO.
    [audio, merge],
  );

  const loop = useCallback(
    async (myGen: number) => {
      try {
        while (alive(myGen)) {
          if (!(await checkpoint(myGen))) return;

          // 1. PLAN — prefer the turn prefetched during the last feedback (no cold wait). On
          // the very first turn there's nothing prefetched, so cover that one load with the
          // "begin" chime instead of silence.
          merge({ phase: 'loading', attempt: null, level: 0 });
          const prefetched = nextPromptRef.current;
          nextPromptRef.current = null;
          let prompt: PromptPacket;
          if (prefetched) {
            prompt = await prefetched.catch(() => api.nextPrompt()); // refetch if the prefetch failed
          } else {
            void playSafe(EARCON.begin); // first turn only — overlaps the cold load
            prompt = await api.nextPrompt();
          }
          if (!alive(myGen)) return;
          setState((s) => ({ ...s, prompt, spend: s.spend + (prompt.costUsd ?? 0) }));

          // 2. TEACHER speaks: setup → taught word (introduce) → classmate (if any)
          merge({ phase: 'teaching' });
          replayRef.current = [prompt.setupAudioUrl, prompt.teach?.modelAudioUrl, prompt.classmateAudioUrl].filter(
            (x): x is string => !!x,
          );
          await playSafe(prompt.setupAudioUrl);
          if (!(await checkpoint(myGen))) return;
          await playSafe(prompt.teach?.modelAudioUrl);
          await playSafe(prompt.classmateAudioUrl);
          if (!(await checkpoint(myGen))) return;

          // 3. YOUR TURN → record until they stop talking → submit (recordMs is only the
          // fixed fallback window when metering is unavailable, e.g. web; on device VAD ends it)
          await playSafe(EARCON.yourTurn);
          const rec = await runListen(myGen, prompt.recordMs ?? 6000);
          if (!alive(myGen)) return;

          // SCORE — loop a soft ambient bed under the wait so it reads as the teacher
          // considering, never a freeze. Stops the instant feedback is ready.
          merge({ phase: 'scoring' });
          const bed = audio.playLoop(EARCON.thinkingBed);
          let attempt: AttemptResult;
          try {
            attempt = await api.submitAttempt(prompt.turnId, rec);
          } finally {
            await bed.stop();
          }
          if (!alive(myGen)) return;
          setState((s) => ({ ...s, attempt, spend: s.spend + (attempt.costUsd ?? 0) }));

          // Prefetch the NEXT turn now — the attempt is persisted, so planTurn sees fresh SRS
          // state, and the feedback below (~3-5s of audio) hides the round-trip entirely.
          const next = api.nextPrompt();
          next.catch(() => {}); // swallow if we stop before consuming it (avoids unhandled rejection)
          nextPromptRef.current = next;

          // 4. FEEDBACK: spoken warm cue → native model → warm earcon
          merge({ phase: 'feedback' });
          replayRef.current = [attempt.correctionAudioUrl, attempt.modelAudioUrl].filter((x): x is string => !!x);
          await playSafe(attempt.correctionAudioUrl);
          await playSafe(attempt.modelAudioUrl);
          await playSafe(attempt.verdict === 'correct' ? EARCON.gotIt : EARCON.again);
          if (!(await checkpoint(myGen))) return;

          // 5. ADVANCE (a breath, then the next turn — SRS decides what resurfaces)
          await sleep(GAP_MS, myGen);
        }
      } catch (e) {
        if (alive(myGen)) merge({ phase: 'error', error: e instanceof Error ? e.message : String(e) });
      }
    },
    [api, audio, checkpoint, merge, playSafe, runListen],
  );

  const start = useCallback(() => {
    gen.current += 1;
    pausedRef.current = false;
    nextPromptRef.current = null; // fresh start always cold-loads turn 1 (with the begin chime)
    void loop(gen.current);
  }, [loop]);

  const stop = useCallback(() => {
    gen.current += 1; // cancels the in-flight loop at its next checkpoint
    pausedRef.current = false;
    nextPromptRef.current = null; // drop any prefetched-but-unused turn (its server row is harmless)
    resumeRef.current?.();
    resumeRef.current = null;
  }, []);

  const pause = useCallback(() => {
    pausedRef.current = true;
  }, []);

  const resume = useCallback(() => {
    pausedRef.current = false;
    resumeRef.current?.();
  }, []);

  /** Replay the current phase's clips (the optional "say that again" gesture). */
  const repeat = useCallback(async () => {
    for (const c of replayRef.current) await playSafe(c);
  }, [playSafe]);

  // Tear down on unmount: cancel the loop so no recorder/timer outlives the screen.
  useEffect(() => stop, [stop]);

  return { state, start, stop, pause, resume, repeat };
}
