/**
 * Client <-> server contract for one self-paced turn. The client never runs the
 * engine; it asks for the next prompt, lets the learner build & speak, submits the
 * recording, and renders the warm feedback. Mirrors the brain's TurnDecision /
 * Feedback but trimmed to what the UI needs (audio URLs resolved server-side).
 */

import type { AudioBlobRef } from '../audio/types';

/** The new block taught on an `introduce` turn — hear + see it before producing. */
export interface TeachBlock {
  surface: string;
  pinyin?: string;
  modelAudioUrl: string;
}

export interface PromptPacket {
  turnId: string;
  /** 'introduce' teaches a new block first; 'recombine' is construct-first */
  action?: 'introduce' | 'recombine';
  /** L1 setup — spoken, and shown as an optional visual aid */
  englishSetup: string;
  setupAudioUrl: string;
  /** present on introduce turns: the new block to hear + see first */
  teach?: TeachBlock;
  /**
   * The target answer — construct-first, so the real server OMITS this before the
   * attempt (the learner must build it). The mock provides it for convenience; the
   * UI must not reveal it pre-attempt.
   */
  targetUtterance?: { surface: string; pinyin?: string; expectedTones?: string };
  /** optional simulated classmate attempt (off by default in Phase 1) */
  classmateAudioUrl?: string;
}

export interface AttemptResult {
  verdict: 'correct' | 'close' | 'off';
  /** one warm cue, generated by the brain — never a score */
  correction: string;
  modelAudioUrl: string;
  decision: 'advance' | 'rebuild' | 'ease';
  /** tone to coach this turn (drives the audio-native tone scaffold), if any */
  toneFocus?: string;
}

export interface SessionApi {
  nextPrompt(): Promise<PromptPacket>;
  submitAttempt(turnId: string, audio: AudioBlobRef): Promise<AttemptResult>;
}
